language: python
python:
    - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - verilator
      - g++-4.9

before_install:
  # BEGIN: coreir installation
  - curl -s -L https://github.com/rdaly525/coreir/releases/latest | grep "href.*coreir.tar.gz" | cut -d \" -f 2 | xargs -I {} wget https://github.com"{}"
  - mkdir coreir_release;
  - tar -xf coreir.tar.gz -C coreir_release --strip-components 1;
  - export PATH=$TRAVIS_BUILD_DIR/coreir_release/bin:$PATH;
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/coreir_release/lib:$LD_LIBRARY_PATH;
  # END: coreir installation

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install --upgrade pytest pytest-cov

script:
  - pip install -e .
  - pytest --cov=silica


after_success:
    - coveralls
