language: python
python:
    - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - verilator
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - g++-4.9

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install --upgrade pytest pytest-cov

script:
  - pip install -e .
  - pytest --cov=silica


after_success:
    - coveralls
