language: python
python:
    - "3.6"

addons:
  apt:
    packages:
      - verilator
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install --upgrade pytest pytest-cov

script:
  - pip install -e .
  - pytest --cov=silica


after_success:
    - coveralls
